### ISSUE TITLE
Appreciation - for cryptography 3.3.1 bug

### ISSUE THREAD

**Issue by MadhavVij** [sgauert/Serious-Games#1]
I don't know where else to write this, but thanks for this comment: https://github.com/pyca/cryptography/issues/5575#issuecomment-730362598
The moderators over there have locked the thread so I couldn't appreciate how much effort your comment saved me.

You can close this issue, lol.

**Comment by sgauert** [comment]
😀thanks for your Feedback and Good luck 😉
